spring.application.name=ms-notificacion
server.port=${SERVER_PORT:8085}

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3313/notificaciones_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC}
spring.datasource.username=${DB_USER:demo}
spring.datasource.password=${DB_PASSWORD:Demo123!}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true